// BuildConfig.h.in - Generated by CMake
#ifndef OSGEARTH_BUILDCONFIG_H
#define OSGEARTH_BUILDCONFIG_H

// If C++11 is available there will be a define here:
#define OSGEARTH_CXX11

// The SOVERSION will be a define here:
#define OSGEARTH_SOVERSION 113

#endif // OSGEARTH_BUILDCONFIG_H

